[package]
name = "text2num"
version = "1.5.3"
authors = ["Romuald Texier-Marcadé <r.texiermarcade@allo-media.fr>"]
edition = "2021"

[lib]
name = "text2num"

[dependencies]
phf = { version = "0.8", features = ["macros"] }
