[package]
name = "text2num-rs"
version = "1.2.0"
authors = ["Romuald Texier-Marcadé <r.texiermarcade@allo-media.fr>"]
edition = "2018"

[lib]
name = "text2num"

[dependencies]
unicode-segmentation = "1.6"
